spring:
  application:
    name: cheongpodo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis
      port: 6379

kakao:
  secret-key: ${KAKAO_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000